### ISSUE TITLE
无法正确删除

### ISSUE THREAD

**Issue by NoverNobida** [WizTeam/WizNoteLite#102]
如图所示的情况，无法正确删除红框部分
![image](https://user-images.githubusercontent.com/46912250/91849375-8939d000-ec8e-11ea-8143-7bd8d81296fa.png)

![1](https://user-images.githubusercontent.com/46912250/91850060-8d1a2200-ec8f-11ea-95af-cf56220ab9dd.gif)

**Comment by Xenaxxx** [comment]
该问题会尽快检查处理，感谢反馈

**Comment by NoverNobida** [comment]
应该是编辑器（vditor）的问题，我关注到wiznote加入了（或者替换？）新的编辑器，应该不存在这个问题。

**Comment by Xenaxxx** [comment]
2.0 版本修复该问题
