### ISSUE TITLE
图片路径无法识别空格

### ISSUE THREAD

**Issue by cloris-cc** [WizTeam/WizNoteLite#103]
您好，当我插入的图片**文件路径存在空格**时，就无法识别为图片了，而是以普通文本出现。
另外，在 typora、editor.md 等编辑器中均并不会出现此情况。
- Lite：
![image](https://user-images.githubusercontent.com/39162684/92491510-e56b9980-f224-11ea-8bf2-546809208134.png)
- Typora：

![image](https://user-images.githubusercontent.com/39162684/92491967-6c207680-f225-11ea-90b0-025ec9cb7706.png)

**Comment by hughdj** [comment]
嗯 同样这个问题

**Comment by WizTeam** [comment]
2.0已经解决
