### ISSUE TITLE
公式$2 x$不能正确显示

### ISSUE THREAD

**Issue by gnwd** [WizTeam/WizNoteLite#104]
$2 x$不能
$x 2$可以
![Selection_023](https://user-images.githubusercontent.com/22853129/93655581-edaeaa80-fa56-11ea-93d5-5d01cd6435fb.png)

**Comment by Xenaxxx** [comment]
感谢反馈，下个版本会修复该问题

![image](https://user-images.githubusercontent.com/4945218/96395477-4f4d6a80-11f7-11eb-924a-fedcabd04f72.png)

**Comment by WizTeam** [comment]
2.0已经解决
