### ISSUE TITLE
标签和笔记的排列顺序

### ISSUE THREAD

**Issue by NoverNobida** [WizTeam/WizNoteLite#105]
标签和笔记是按什么顺序排列的？查看标签和笔记的时候无法快速找到相应标签和笔记。笔记的顺序似乎是最近修改的排在最上面，但是实际使用中， 点击“全部笔记”，发现有时候最上面的并不是最近修改的，点击(有二级标签的)一级标签，有时候也找不到相应笔记。
- 希望可以按照时间、首字母等顺序排列标签；
- 修复"点击一级标签，有时不显示二级标签笔记"的错误;
- 希望可以拖动笔记到相应标签上从而改变标签；
- 希望可以多选笔记（无法批量删除或者导出）；
- 希望可以仅限于一级标题下面一行添加标签，否则在正文中有时候要使用“#”字符，但是会被识别为标签。

**Comment by WizTeam** [comment]
标签是按照名称排序，笔记是按照修改时间排序。
找不到笔记的问题，2.0已经解决。

**Comment by NoverNobida** [comment]
![image](https://user-images.githubusercontent.com/46912250/97825400-7fb5fe00-1cf9-11eb-9861-87ace4da6188.png)
如图，没有按照名称排列啊。
