### ISSUE TITLE
新建无图片的文件时，导出为Markdown功能报错

### ISSUE THREAD

**Issue by Askorter** [WizTeam/WizNoteLite#106]
### 一、问题描述
使用"导出为Markdown"功能时出现报错弹窗，且文件导出失败。

截图：

<img width="498" alt="screencut" src="https://user-images.githubusercontent.com/17570564/94161350-2a93fa80-feb8-11ea-92d9-9e6c5efb58e5.png">

### 二、遇到问题的环境
macOS Mojave 10.14.6

### 三、如何复现
新建一个不包含图片的文件，随便输入几行字，点击“导出为Markdown”。
注：必须保证文件是完全新建的且没有插入过图片。

### 四、问题原因
通过开发者工具进行断点调试，发现是在向主线程发送了'writeToMarkdown'事件后报的错，进入包文件中查找，在 ./src/main/api.js 文件中找到了相关事件的处理方法，然后发现在处理方法中，对于生成的需要导出的文件的资源目录路径，在没有判断路径是否存在的情况下，直接进行了目录文件读取操作，导致了在需要导出的文件实际上并没有文件资源目录的情况下（也就是没有插入过图片或其他资源），会直接抛出error，并且生成md文件失败。

文件路径（源代码中）：src/main/api.js
问题代码截图：

<img width="680" alt="screencut_2" src="https://user-images.githubusercontent.com/17570564/94162529-64b1cc00-feb9-11ea-8f37-7f20ee0b2b1f.png">

### 五、修复方法
将原代码基础上添加resourcePath路径判空即可，例如：
```
  const resourcePath = await paths.getNoteResources(userGuid, kbGuid, noteGuid);
+ let files = [];
+ if (fs.existsSync(resourcePath)) {
     files = await fs.readdir(resourcePath);
+ }
```

**Comment by awkj** [comment]
既然都是程序员，都提 issue 有 fix 方案了，就直接提 PR 吧

**Comment by WizTeam** [comment]
新版本会解决，谢谢！

**Comment by WizTeam** [comment]
2.0已经解决
