### ISSUE TITLE
2.0 版本为什么无法同步已经有的笔记呀

### ISSUE THREAD

**Issue by Lyn6969** [WizTeam/WizNoteLite#113]
![image](https://user-images.githubusercontent.com/42564665/98098101-dc1b4800-1ec8-11eb-9997-0dfeb60e6e4c.png)
已经登录了，但是没办法同步到已经有的笔记

**Comment by Hongki-Long** [comment]
同问，为什么咧？

**Comment by Lyn6969** [comment]
> 同问，为什么咧？

不会是不互通吧，那也太扯了

**Comment by WizTeam** [comment]
lite客户端里面仅显示lite创建的笔记。

在为知笔记标准客户端里面，会显示lite创建的笔记。

**Comment by Lyn6969** [comment]
> lite客户端里面仅显示lite创建的笔记。
> 
> 在为知笔记标准客户端里面，会显示lite创建的笔记。

好吧，我还以为能代替标准客户端呢

**Comment by Hongki-Long** [comment]
那有没有办法将客户端的笔记同步到lite里面

**Comment by zhzhdwy** [comment]
是啊，以为可以代替客户端，lite只能放放了
