### ISSUE TITLE
markdown渲染问题

### ISSUE THREAD

**Issue by Z-Echo** [WizTeam/WizNoteLite#16]
没办法渲染[TOC]这种导航条
![image](https://user-images.githubusercontent.com/52945898/87748939-e20df000-c829-11ea-9e27-03cc895470a6.png)

**Comment by WizTeam** [comment]
有计划改进，谢谢！

**Comment by WizTeam** [comment]
增加了目录支持（不是[toc]这种语法）。从1.2版本开始支持目录
