### ISSUE TITLE
画类图时，一到花括号就会卡死

### ISSUE THREAD

**Issue by ystyle** [WizTeam/WizNoteLite#17]
系统信息:
![2020-07-17_13-16](https://user-images.githubusercontent.com/4478635/87751130-eccb8380-c82f-11ea-831d-2f103b924147.png)

```代码
classDiagram
  class DateEntity // {} // 一输入这个就卡死
  class User {
    String Name
    String Password
    String address
    Valid()
  }
```

另外就是双击无法打开，只能在命令行打开。

**Comment by ystyle** [comment]
建议: 容器边框做下阴影， 白色时完全看不出来边框在哪。。。

**Comment by WizTeam** [comment]
> 系统信息:
> ![2020-07-17_13-16](https://user-images.githubusercontent.com/4478635/87751130-eccb8380-c82f-11ea-831d-2f103b924147.png)
> 
> ```
> classDiagram
>   class DateEntity // {} // 一输入这个就卡死
>   class User {
>     String Name
>     String Password
>     String address
>     Valid()
>   }
> ```
> 
> 另外就是双击无法打开，只能在命令行打开。

可以拍一个视频吗？我这里不清楚怎么重现出来。

双击的问题，是不是AppImage文件没有可执行的权限？我在ubuntu上面没问题

**Comment by WizTeam** [comment]
> 建议: 容器边框做下阴影， 白色时完全看不出来边框在哪。。。

哪一个容器？
谢谢！

**Comment by ystyle** [comment]
> > 建议: 容器边框做下阴影， 白色时完全看不出来边框在哪。。。
> 
> 哪一个容器？
> 谢谢！

就是整个窗口的边缘加个阴影，在白色主题和桌面是白色时，比较容易分清边框， 不然一不小心就点到外面去了

**Comment by WizTeam** [comment]
> > > 建议: 容器边框做下阴影， 白色时完全看不出来边框在哪。。。
> > 
> > 
> > 哪一个容器？
> > 谢谢！
> 
> 就是整个窗口的边缘加个阴影，在白色主题和桌面是白色时，比较容易分清边框， 不然一不小心就点到外面去了

明白了，这个和linux版本有关。我们考虑一下加一个边框看看。

**Comment by ystyle** [comment]
gif 录屏： 1. 演示了双击打不开的问题 2. 类图一输入`{`号就卡死的问题
![Peek 2020-07-17 15-37](https://user-images.githubusercontent.com/4478635/87761346-e0e9bc80-c843-11ea-996a-5385a28a696a.gif)

**Comment by WizTeam** [comment]
> gif 录屏： 1. 演示了双击打不开的问题 2. 类图一输入`{`号就卡死的问题

已经重现，会尽快检查的，谢谢！

**Comment by WizTeam** [comment]
1.2版本已经解决
