### ISSUE TITLE
导出PDF文件无反应

### ISSUE THREAD

**Issue by tanglei5** [WizTeam/WizNoteLite#18]
![image](https://user-images.githubusercontent.com/23393070/87751730-4da78b80-c831-11ea-860b-37b4af4fcb45.png)

一直停留在正在生成

**Comment by WizTeam** [comment]
可以点击左上角图标，选择显示开发工具，看看有没有报错。
如果方便的话，可以在vs code里面调试一下看看问题

**Comment by Xenaxxx** [comment]
@tanglei5 调试后是否有具体错误信息，请截图或复制提供

**Comment by tanglei5** [comment]
> @tanglei5 调试后是否有具体错误信息，请截图或复制提供

![image](https://user-images.githubusercontent.com/23393070/88746601-7e67b900-d17f-11ea-8643-37a26ee17ba9.png)

只看到这个

**Comment by WizTeam** [comment]
奇怪，这个没有错误生成，你那里方便调试吗？需要开发环境

**Comment by tanglei5** [comment]
我不是很清楚要怎么调试

**Comment by WizTeam** [comment]
可以按照readme来搭建开发环境。有问题可以加我微信(stevewei2006)。

**Comment by WizTeam** [comment]
无进一步反馈，关闭
