### ISSUE TITLE
产品经理出来挨打

### ISSUE THREAD

**Issue by sunqb** [WizTeam/WizNoteLite#19]
下载下来使用了一下，总结下感受。
优点：简洁，快速。
缺点：编辑页面和预览页面在一起，很不好用。例如我输入完 - xxx文字  回车后自动就展示 . 不会展示markdown源码了。很难受。这点过于替用户着想了。
定位：这个产品的定位我认为定位工具更合适，没有和以前的打通，这个也是很不舒服的地方。

**Comment by WizTeam** [comment]
Lite版本设计的初衷就是一个即时渲染的markdown编辑器，所以会尽可能展示渲染后的结果。

**Comment by sunqb** [comment]
不知道有没有看过 marp这个开源产品，有可能是先入为主，更容易接受这种方式。![image](https://user-images.githubusercontent.com/5319644/87758310-cfea7c80-c83e-11ea-881c-135d5d8cd365.png)

**Comment by WizTeam** [comment]
> 不知道有没有看过 marp这个开源产品，有可能是先入为主，更容易接受这种方式。![image](https://user-images.githubusercontent.com/5319644/87758310-cfea7c80-c83e-11ea-881c-135d5d8cd365.png)

不同的产品形态，看个人习惯了。

**Comment by AriaLyy** [comment]
对为知的社区版本不要抱有太大的希望，特别是社区版，看看残废的mac版本以及linux版本就知道了

**Comment by TiaossuP** [comment]
这个产品本来就是对标 Typora 的吧？
我倒是觉得 marp 这种做起来简单得多，Typora 之前的大多数 markdown 编辑器都是这种。
