### ISSUE TITLE
希望左边笔记列表的宽度可调

### ISSUE THREAD

**Issue by ttttmr** [WizTeam/WizNoteLite#21]
希望左边笔记列表的宽度可调，或者可以收起

![image](https://user-images.githubusercontent.com/32825326/87795557-d3035e00-c87a-11ea-9bfd-8e518e090b8c.png)

**Comment by wizweishijun** [comment]
有计划，谢谢

**Comment by Xenaxxx** [comment]
1.4.1 版本支持通过快捷键设置视图显示，Ctrl + 1 = 仅显示正文

可到 AppStore 或 微软应用市场 更新
本地安装包下载地址：https://support.qq.com/products/174045/faqs/73889
