### ISSUE TITLE
希望MarkDown增加目录&& 图片选中

### ISSUE THREAD

**Issue by duwanjiang** [WizTeam/WizNoteLite#22]
1. 希望增加Markdown的目录，便于跳转
2. Markdown中的图片不太适合操作，特别是像更换图片时，直接点击图片没有任何反应，必须要点击图片的头部，而且没有提示，很难找到

**Comment by wizweishijun** [comment]
谢谢，会考虑改进的

**Comment by duwanjiang** [comment]
不谢，我是Wiz的粉丝 嘻嘻

**Comment by WizTeam** [comment]
目录功能在1.2增加了。
图片选中，替换功能，在1.4版本增加
