### ISSUE TITLE
希望会有双链的功能

### ISSUE THREAD

**Issue by elieye** [WizTeam/WizNoteLite#24]
1. 建议跟进一下双向链接
2. 适当增加一下编辑页面的宽度
3. 希望可以增加读取本地文件夹功能

**Comment by wizweishijun** [comment]
双向链接已经在计划中了。

读取本地文件夹的是什么意思呢？谢谢

**Comment by elieye** [comment]
> 双向链接已经在计划中了。
> 
> 读取本地文件夹的是什么意思呢？谢谢

就是将lite作为本地笔记软件，读取本地文件夹里的md文件，就类似obesidian、zettlr、typora的文件管理方式。

**Comment by wizweishijun** [comment]
明白了。这个之前考虑过，主要有两个问题，就是数据同步和图片，不太好解决。

不过我们有计划提供导入md文件的功能。
谢谢

**Comment by elieye** [comment]
> 明白了。这个之前考虑过，主要有两个问题，就是数据同步和图片，不太好解决。
> 
> 不过我们有计划提供导入md文件的功能。
> 谢谢

谢谢您的解答！期待lite能做的更完善OvO。
