### ISSUE TITLE
在wizlite中记录的笔记无法与typora同步

### ISSUE THREAD

**Issue by ghl116** [WizTeam/WizNoteLite#25]
1、在wizlit中新建笔记
2、同步到wiz笔记中，通过typora编辑，保存
3、同步到wizlit中后，笔记变成了空白

**Comment by wizweishijun** [comment]
目前不要在wiz里面编辑lite的笔记，会造成数据损坏。lite的笔记只能在lite里面编辑。可以在wiz里面阅读。

**Comment by ghl116** [comment]
@wizweishijun  后续会考虑到数据的打通吗？毕竟都是markdown

**Comment by wizweishijun** [comment]
> @wizweishijun  后续会考虑到数据的打通吗？毕竟都是markdown

后面会考虑的。谢谢
