### ISSUE TITLE
1.1windows版启动报错。系统win7,之前用1.0版没问题。

### ISSUE THREAD

**Issue by bleachgh** [WizTeam/WizNoteLite#26]
wizsqlite3.node is not a valid win32...
![image](https://user-images.githubusercontent.com/10919527/87842864-5dcb7380-c8e2-11ea-972a-e9d53a5c89da.png)

**Comment by wizweishijun** [comment]
正在解决中。如果方便，可以自己clone代码打包。谢谢

**Comment by wizweishijun** [comment]
已经更新，重新下载试试。

**Comment by bleachgh** [comment]
> 已经更新，重新下载试试。
为知团队不错，反应很快。下了新版可以使用了，期待越做越好，markdown笔记这块市场很大。
