### ISSUE TITLE
【bug】ctrl +"+" 视图不能放大

### ISSUE THREAD

**Issue by Johnwjl** [WizTeam/WizNoteLite#28]
WizNote Lite Windows 版 有个bug , 整个视图 ctrl+ "-" , 可以缩小，
但是反之， ctrl +"+" 不能放大，
这个bug很严重啊，缩小之后不能放大，直接影响使用了，现在直接用不了。
截图如下，望速解决

![image](https://user-images.githubusercontent.com/17572255/87849960-27f8b000-c91f-11ea-95a3-961232d5d0f2.png)

**Comment by wizweishijun** [comment]
可以试试ctrl shift +
看看是否可以

**Comment by Johnwjl** [comment]
版本号 1.1.0
![image](https://user-images.githubusercontent.com/17572255/87850145-8d996c00-c920-11ea-808e-b7d6cde02d87.png)

**Comment by Johnwjl** [comment]
> 可以试试ctrl shift +
> 看看是否可以
可以了，感谢
