### ISSUE TITLE
编辑器丢失光标焦点

### ISSUE THREAD

**Issue by 88250** [WizTeam/WizNoteLite#34]
刚从 Windows App Store 下载的，登录后会出现焦点丢失问题。

重现步骤：

1. 正常编辑
2. 点击同步，弹出受限
3. 编辑光标丢失
4. 切换到其他窗口后切换回来焦点恢复

录屏演示：

![issue](https://user-images.githubusercontent.com/873584/88006704-dc245180-cb3e-11ea-9ea5-fcf66174d8a8.gif)

**Comment by wizweishijun** [comment]
会尽快检查的，谢谢

**Comment by WizTeam** [comment]
代码已经提交到dev分支，方便的话可以测试看看还有没有这个问题。
谢谢！

**Comment by Xenaxxx** [comment]
如该问题还存在，请重开 issue 反馈
