### ISSUE TITLE
代码块内代码不能自动补全

### ISSUE THREAD

**Issue by kanghaov** [WizTeam/WizNoteLite#46]
这一点typora做的不错，可以参考下

**Comment by WizTeam** [comment]
已经记录，谢谢！

**Comment by kanghaov** [comment]
加油，很喜欢为知笔记

**Comment by fwindpeak** [comment]
我遇到的问题是：
+ 代码块内编辑不支持tab缩进，也就是按了tab后没有插入4个空格
+ 代码块内编辑时不支持实时语法高亮

可以稍微关注一下，第二点可能需要更换编辑控件了 😓

**Comment by WizTeam** [comment]
如果支持代码编辑功能的话，可能会引入比较复杂的编辑组件，或许会导致响应速度比较慢。

**Comment by Vanessa219** [comment]
@fwindpeak 
* 需要 <kbd>tab</kbd> 输入四个空格的话可以让开发人员在初始化 Vditor 中配置 `options.tab='    '` 即可，或者将这个做为用户的配置项
* 实时语法高亮目前只能在代码块下方查看
![image](https://user-images.githubusercontent.com/970828/89093309-c428b980-d3eb-11ea-9aef-fb6958b76a45.png)

**Comment by wizweishijun** [comment]
> @fwindpeak 
> 
> * 需要 <kbd>tab</kbd> 输入四个空格的话可以让开发人员在初始化 Vditor 中配置 `options.tab='    '` 即可，或者将这个做为用户的配置项
> 
> * 实时语法高亮目前只能在代码块下方查看
> 
> ![image](https://user-images.githubusercontent.com/970828/89093309-c428b980-d3eb-11ea-9aef-fb6958b76a45.png)
> 
> 
> 
> 
> 
> 

感谢大佬回复。以后会增加选项。谢谢
