### ISSUE TITLE
不晓得这个版本的意义在哪里？

### ISSUE THREAD

**Issue by dwSun** [WizTeam/WizNoteLite#49]
为知是打算重构客户端还是只是推出一个新的客户端，双客户端并行？

全功能版本客户端标榜的也是笔记软件，支持markdown。这个Lite版本则是标榜markdown为主的。那么后续为知团队打算怎么发展呢？

标准客户端安乐死？

**Comment by WizTeam** [comment]
Lite专注于Markdown写作。
标准客户端则注重于全功能。
两个版本都会存在并继续发展。

**Comment by dwSun** [comment]
我个人猜测，是不是全功能版本使用的markdown不好用，同时开发完善难度大，成本高是，所以才单独开发了一个版本，使用了基于web的技术。

**Comment by Ranler** [comment]
标准版关注于资料收集，Lite版专注于写作，支持！

**Comment by dwSun** [comment]
如果是这样的话，有个建议，可以考虑像 WizNotePlus 的那种方式，这个lite做编辑器，而全功能版本只做显示和管理。不然两个版本并行，真的很麻烦，特别是lite没有跟标准版的目录结构共通。
