### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ziyue7575** [WizTeam/WizNoteLite#50]
1. 左侧两栏都能隐藏
2. 添加`[TOC]`目录功能
3. 拥有为知笔记的编辑功能的快捷键
4. 为知笔记可以将lite作为外部编辑器打开编辑markdown笔记

**Comment by WizTeam** [comment]
2: 1.2版本已经增加目录功能
其他功能已经记录，谢谢！

**Comment by WizTeam** [comment]
> 1. 左侧两栏都能隐藏

已经增加菜单和快捷键Ctrl+1,将在1.4版本实现。

**Comment by ziyue7575** [comment]
期待(*❦ω❦)
