### ISSUE TITLE
希望可以支持 kbd 标签

### ISSUE THREAD

**Issue by John-Chan** [WizTeam/WizNoteLite#56]
比如这个 https://stackoverflow.com/a/36098644/1118665

效果是这个样子的
![KBD](https://user-images.githubusercontent.com/2360910/88500951-9e22a400-cffc-11ea-9962-56383c3f2c6a.png)

**Comment by WizTeam** [comment]
现在好像没有标准的语法支持kbd标签

**Comment by John-Chan** [comment]
好的，如果做不到也只能作罢了。

目前使用起来感觉还不如 `Typora` 好用，感谢开源，希望越做越好。

**Comment by 88250** [comment]
@WizTeam @John-Chan 我想以后应该可以支持的，`<kbd>` 是行级 HTML 节点，可以单独为 `<kbd>` 标签做渲染效果。

**Comment by WizTeam** [comment]
实现不难，主要是现在没有标准的语法。

**Comment by 88250** [comment]
目前大致可以做到这样的效果：

![issue](https://user-images.githubusercontent.com/873584/88658259-b9c5a180-d105-11ea-94e0-365fb3d6d7c2.gif)

后续关于 HTML 标签方面的优化：

* 输入时自动完成闭合
* 光标在标签中时应该同时展开开始 `<tag>` 节点和结束 `</tag>` 节点

**Comment by wizweishijun** [comment]
> 目前大致可以做到这样的效果：
> 
> 
> 
> ![issue](https://user-images.githubusercontent.com/873584/88658259-b9c5a180-d105-11ea-94e0-365fb3d6d7c2.gif)
> 
> 
> 
> 后续关于 HTML 标签方面的优化：
> 
> 
> 
> * 输入时自动完成闭合
> 
> * 光标在标签中时应该同时展开开始 `<tag>` 节点和结束 `</tag>` 节点
> 
> 
> 
> 

直接用html标签不太好，现在的编辑器对html标签支持的不够。我们考虑一下。谢谢

**Comment by Xenaxxx** [comment]
最新版本已支持
