### ISSUE TITLE
改善建议

### ISSUE THREAD

**Issue by kuqu00** [WizTeam/WizNoteLite#57]
**WizNoteLite还有很大的改善空间。**

1. 在 无序列表/有序列表 之间插入内容，上面总会有一个标签无法删除
![image](https://user-images.githubusercontent.com/26627166/88603359-442ae880-d0a7-11ea-97af-7e107ff24d15.png)

2. 无法创建笔记本的情况下，只有 AllNotes ，Starred notes ，Trash 无法满足需求。至少我希望有一个“无标签笔记”这个选项
![image](https://user-images.githubusercontent.com/26627166/88603493-aa177000-d0a7-11ea-907c-e8a6250c73ec.png)

3. typora的确美观，但是我更喜欢vnote这样的Markdown编辑器，希望可以借鉴VNote的优点
地址：https://github.com/tamlok/vnote

**Comment by WizTeam** [comment]
收到已经记录，谢谢！

**Comment by WizTeam** [comment]
第一个问题，把光标定位在空白list上面，然后按下退格键就可以删除空白行了

**Comment by kuqu00** [comment]
> 第一个问题，把光标定位在空白list上面，然后按下退格键就可以删除空白行了

1. 原来是这样的。
● 方便
● 简介
● 即时预览

2. 我想将 简介和即时预览 分开
我想要的是这样的结果:
● 方便
● 简介

新的内容

● 即时预览

3.  软件最终的结果是这样的

● 方便
● 简介
●
新的内容

● 即时预览

> 这个点永远都无法删除，除非我把  ”即时预览“ 列表删除了（如果后面还有列表也要一起删除）， 输入新的内容，在添加上去才行

**Comment by Xenaxxx** [comment]
@kuqu00 

1. 光标在列表项目后，回车，此时会新增一个列表项
2. 再次双击回车，光标从无序列表中跳出变为普通文本
3. 光标定位至空白列表处（圆点后面），按退格删除

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gh6tvf3275g30dg09s1iq.gif)

**Comment by kuqu00** [comment]
> @kuqu00
> 
> 1. 光标在列表项目后，回车，此时会新增一个列表项
> 2. 再次双击回车，光标从无序列表中跳出变为普通文本
> 3. 光标定位至空白列表处（圆点后面），按退格删除
> 
> ![](https://camo.githubusercontent.com/eca9849e0e262c4e24a4c0f386e984506017e827/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c6c79316768367476663332373567333064673039733169712e676966)

好的，谢谢
