### ISSUE TITLE
UWP版本左边栏显示

### ISSUE THREAD

**Issue by tjliamwang** [WizTeam/WizNoteLite#62]
如图，左边栏上方显示Wiz图标、“Wiznote Lite”和VIP图标，略显繁琐，且单栏无法单独调整，在整体合适的大小该处显示错乱、不全。
显示器为1080P 13.3英寸笔记本。
![图片](https://user-images.githubusercontent.com/46560419/88744888-3777c480-d17b-11ea-9124-f46a92aa0add.png)

**Comment by WizTeam** [comment]
谢谢！会尽快处理

**Comment by WizTeam** [comment]
1.4版本解决
