### ISSUE TITLE
Lite是不会同步笔记图片到为知笔记吗？

### ISSUE THREAD

**Issue by TyrantLucifer** [WizTeam/WizNoteLite#63]
有个疑问哈，产品简介里说无需图床图片直接显示，我认为这个功能是自动将图片上传到为知的图床，当我按下同步按钮的时候，笔记和图片将一块提交给为知笔记的服务器，我在自己的账号笔记中可以看到新写的笔记和笔记中的图片，但事实上我只能看到自己的笔记，无法看到笔记中的图片，想请教一下，是我的理解有问题还是我的操作方式不对呢？

**Comment by WizTeam** [comment]
图片是如何插入lite里面的呢？是插入本地图片吗？

**Comment by TyrantLucifer** [comment]
通过截图放在剪贴板，直接Ctrlv粘在笔记中的呢。

**Comment by WizTeam** [comment]
应该是可以的。在为知笔记网页版看不到图片吗？

**Comment by TyrantLucifer** [comment]
我在客户端中看不到图片。

**Comment by WizTeam** [comment]
可以加我微信看看 stevewei2006

**Comment by WizTeam** [comment]
暂未重现出来，等待继续测试
