### ISSUE TITLE
后台运行

### ISSUE THREAD

**Issue by NoverNobida** [WizTeam/WizNoteLite#67]
希望可以后台运行，通过任务栏图标快速启动。目前关闭软件后，重新打开软件速度较慢。

**Comment by NoverNobida** [comment]
另外，中文输入有较大问题，输入时，输入法候选框会在软件之外，即电脑左上角，输入后再次打字才能恢复到光标位置，再次输入又会出现问题，如此循环往复。

**Comment by WizTeam** [comment]
> 另外，中文输入有较大问题，输入时，输入法候选框会在软件之外，即电脑左上角，输入后再次打字才能恢复到光标位置，再次输入又会出现问题，如此循环往复。

用的是什么输入法？

**Comment by NoverNobida** [comment]
QQ输入法其他输入法未尝试。
![image](https://user-images.githubusercontent.com/46912250/88910986-c83fc480-d28f-11ea-8082-28f1b8dd5cba.png)

**Comment by WizTeam** [comment]
> 希望可以后台运行，通过任务栏图标快速启动。目前关闭软件后，重新打开软件速度较慢。

就是关闭窗口的时候，缩小到托盘区吧。

**Comment by WizTeam** [comment]
> QQ输入法其他输入法未尝试。
> ![image](https://user-images.githubusercontent.com/46912250/88910986-c83fc480-d28f-11ea-8082-28f1b8dd5cba.png)

谢谢！
会尽快测试

**Comment by NoverNobida** [comment]
> 就是关闭窗口的时候，缩小到托盘区吧。
是的。感觉有助于快速启动，就像经典版本一样。

**Comment by NoverNobida** [comment]
另外，移动端之后会怎么处理与电脑lite端的关系？目前移动端是将lite版的笔记归为一个文件夹，内容为Markdown格式。但是一方面没有标签，也就无法进行分类查看，另一点是内容上正文开头还是会有一个一级标题，标签也会显示为一级标题，很不美观。

**Comment by WizTeam** [comment]
> 另外，移动端之后会怎么处理与电脑lite端的关系？目前移动端是将lite版的笔记归为一个文件夹，内容为Markdown格式。但是一方面没有标签，也就无法进行分类查看，另一点是内容上正文开头还是会有一个一级标题，标签也会显示为一级标题，很不美观。

有计划开源一个lite的移动客户端工程

**Comment by WizTeam** [comment]
已经增加，1.4版本支持

**Comment by NoverNobida** [comment]
我在软件反馈链接：[https://support.qq.com/products/174045/](https://support.qq.com/products/174045/)上面还反馈了一些问题，希望能看到。

**Comment by WizTeam** [comment]
> 我在软件反馈链接：https://support.qq.com/products/174045/上面还反馈了一些问题，希望能看到。

已经记录
