### ISSUE TITLE
数据丢失问题

### ISSUE THREAD

**Issue by kuqu00** [WizTeam/WizNoteLite#77]
wiznote，在Lite文件夹中编辑md文件，已经保存同步到服务器了。打开wiznotelite会丢失数据，部分数据无法找回。

![image](https://user-images.githubusercontent.com/26627166/89093964-90509280-d3f1-11ea-83b9-317cace50704.png)

照成以上的结果是在wiznote编辑wiznotelite中创建的文件，在打开wiznotelite后，笔记内容会全部丢失，希望尽快修复，找出问题。具体情况我也是不是很清楚，但是发生过几次了

**Comment by kuqu00** [comment]
还有几个问题
1. wiznotelite会添加版本控制的功能吗？
2. 是否考虑扩充markdown的功能，比如添加录音文件功能，点击录音文件会自动播放，不需要下载到本地或者用本地软件才能播放。
3.是否考虑添加主题样式功能。
我知道项目在完善阶段，但是我用起来太虐心了

**Comment by wizweishijun** [comment]
> wiznote，在Lite文件夹中编辑md文件，已经保存同步到服务器了。打开wiznotelite会丢失数据，部分数据无法找回。
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/26627166/89093964-90509280-d3f1-11ea-83b9-317cace50704.png)
> 
> 
> 
> 照成以上的结果是在wiznote编辑wiznotelite中创建的文件，在打开wiznotelite后，笔记内容会全部丢失，希望尽快修复，找出问题。具体情况我也是不是很清楚，但是发生过几次了

目前不支持在完整版本里面编辑lite的笔记。

**Comment by wizweishijun** [comment]
> 还有几个问题
> 
> 1. wiznotelite会添加版本控制的功能吗？
> 
> 2. 是否考虑扩充markdown的功能，比如添加录音文件功能，点击录音文件会自动播放，不需要下载到本地或者用本地软件才能播放。
> 
> 3.是否考虑添加主题样式功能。
> 
> 我知道项目在完善阶段，但是我用起来太虐心了

1，2，3都有计划增加，谢谢。

**Comment by NoverNobida** [comment]
@WizTeam 请问是否考虑“附件”功能？通过单独的按钮查看附件，或者直接显示为笔记中的超链接，点击可查看附件或下载。
