### ISSUE TITLE
与wiznote的同步问题 

### ISSUE THREAD

**Issue by zongka** [WizTeam/WizNoteLite#78]
wiznote的老用户了，以前写Markdown都是用typora做为编辑器来编辑wiznote的md文件。wiznote lite不能像typora一样作为一个外部的编辑器吗，就算不能这么操作。用户可以将想要编辑的Md文件拉入Lite文件夹进行编写，编写完再拉出到对应的文件夹进行归档。终不能所有的md都用tag来分档吧。

**Comment by WizTeam** [comment]
有计划增加类似的功能
