### ISSUE TITLE
删除文本时的严重问题

### ISSUE THREAD

**Issue by NoverNobida** [WizTeam/WizNoteLite#85]
出现如下问题：
![1](https://user-images.githubusercontent.com/46912250/89376945-6665db80-d723-11ea-8bb0-62821552c6fe.gif)

文字不仅没有删除，顺序反而错乱，当出现 `第一段第一行前一段文字被删除而留下这一空白段落` 的时候，删除的时候文本严重错乱。

**Comment by NoverNobida** [comment]
一个比较奇葩的错误，图中这一特定的情况可能一般不会遇到，但是也许会出现类似的、由同一原因造成的其他错误，只是还没有发现。
是[vditor](https://github.com/Vanessa219/vditor)产生的错误，vditor中可复现这一错误。
建议从众多开源的所见即所得Markdown编辑器中选择更为成熟的方案，替换vditor或者添加到选择当中。

**Comment by WizTeam** [comment]
谢谢！会尽快解决

**Comment by WizTeam** [comment]
2.0已经更换编辑器。
