### ISSUE TITLE
WizNoteLite 添加图片会导致安卓端打开该笔记初始化崩溃

### ISSUE THREAD

**Issue by awkj** [WizTeam/WizNoteLite#88]
如果删除 WizNoteLite  中的图片则恢复正常，但如果在 安卓客户端添加图片，则 WizNoteLite 中不能正确渲染出来

**Comment by WizTeam** [comment]
已经确认，会尽快处理，谢谢！

**Comment by WizTeam** [comment]
android客户端问题已经修复。
目前请不要在客户端里面编辑lite的笔记。
