### ISSUE TITLE
「导出为 Markdown」功能无效

### ISSUE THREAD

**Issue by Airsaid** [WizTeam/WizNoteLite#90]
WizNoteLite 版本：1.4.1

MacOS 版本：10.15.4 (19E287)

复现路径：

在编辑器页面点击右侧小飞机图标 -> 选择 导出为 Markdown -> 选择保存的路径 -> 点击存储。

路径下并没有 .md 的文件，没有任何效果。

期望结果：

点击存储后，对应的路径下生成 .md 的文件。

**Comment by wizweishijun** [comment]
测试没问题，方便微信联系吗？谢谢

**Comment by Airsaid** [comment]
好的，我的微信：wx5504502

**Comment by WizTeam** [comment]
1.5 已经修复这个问题。

是因为mac下面权限问题。需要申请对下载文件夹完全读写的控制权限。
