### ISSUE TITLE
macOS 暗黑模式下，mermaid 适配问题

### ISSUE THREAD

**Issue by bujige** [WizTeam/WizNoteLite#92]
macOS 暗黑模式下，mermaid 公式渲染效果不佳。部分字样看不清楚，背景色对比度不足。
![Xnip2020-08-11_14-31-30](https://user-images.githubusercontent.com/18569557/89865021-8bed5c00-dbdf-11ea-8bbd-72dc7f0b6f19.jpg)

**Comment by wizweishijun** [comment]
收到，会进行处理的。谢谢

**Comment by WizTeam** [comment]
2.0已经解决
