### ISSUE TITLE
不支持私服的https？

### ISSUE THREAD

**Issue by ruinades** [WizTeam/WizNoteLite#99]
私服改为https不能登录，为知笔记的客户端也是这样，只能用http么？

**Comment by wizweishijun** [comment]
应该是你的服务器配置问题。是用的自签名的证书吗？


发自我的iPhone

**Comment by NoverNobida** [comment]
很大可能性是反向代理的配置问题，你可以在看看官方的配置HTTPS的文档。如果你用的是NGINX，我用的是如下配置：
```nginx
server {
  listen 80;
  listen  443 ssl;
  server_name           n.nover.xyz; 
  ssl_certificate    /path/to/certificate/certificate.pem;
  ssl_certificate_key    /path/to/key/key.pem; 
  ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers           HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;
  
  if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
  
  location / {
    proxy_pass http://localhost:5000; 
    proxy_http_version 1.1;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header x-wiz-real-ip $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto "https";
  }
}

**Comment by ruinades** [comment]
> 应该是你的服务器配置问题。是用的自签名的证书吗？ 发自我的iPhone
> […](#)
> 在 2020年8月27日，上午8:55，ruinades ***@***.***> 写道： ﻿ 私服改为https不能登录，为知笔记的客户端也是这样，只能用http么？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，自签证书

**Comment by ruinades** [comment]
> 很大可能性是反向代理的配置问题，你可以在看看官方的配置HTTPS的文档。如果你用的是NGINX，我用的是如下配置：
> 
> ```nginx
> server {
>   listen 80;
>   listen  443 ssl;
>   server_name           wiz.yourdomain.com; 
>   ssl_certificate    /path/to/certificate/certificate.pem;
>   ssl_certificate_key    /path/to/key/key.pem; 
>   ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
>   ssl_ciphers           HIGH:!aNULL:!MD5;
>   ssl_prefer_server_ciphers on;
>   ssl_session_cache shared:SSL:10m;
>   ssl_session_timeout 10m;
>   
>   if ($server_port !~ 443){
>         rewrite ^(/.*)$ https://$host$1 permanent;
>     }
>   
>   location / {
>     proxy_pass http://localhost:5000; 
>     proxy_http_version 1.1;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header x-wiz-real-ip $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Forwarded-Proto "https";
>   }
> }
> ```

谢谢，我用的官方的docker，浏览器可以https访问，为知客户端（报错：无法获取服务器信息）和lite客户端都（报错：无法获取服务器版本：self signed certificate）不可以登录。

**Comment by NoverNobida** [comment]
那可能就是客户端不能用自签证书，你试试用let’s encrypt、腾讯云或者阿里云的免费证书试一试。

**Comment by ruinades** [comment]
> 那可能就是客户端不能用自签证书，你试试用let’s encrypt、腾讯云或者阿里云的免费证书试一试。

老师好，换了lets的证书，仍旧提示“无法获取服务器版本：unble to verify the first certificate”。
还有着吗

**Comment by NoverNobida** [comment]
那只能找官方联系方式问问了，他们应该会有解答的经验。在issue里面可能不会及时回复，也不方便解决问题。

**Comment by ruinades** [comment]
> 那只能找官方联系方式问问了，他们应该会有解答的经验。在issue里面可能不会及时回复，也不方便解决问题。

谢谢回复

**Comment by WizTeam** [comment]
服务的问题，和客户端无关
